version: 3.7"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: webvirtbackend:dev
    hostname: backend
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - .:/app
    command: python3 manage.py runserver 0:8000
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: webvirtcloud
      DB_USER: django
      DB_PASSWORD: django
      PYTHONOPTIMIZE: 1
      ANSIBLE_HOST_KEY_CHECKING: 0
      ANSIBLE_PARAMIKO_LOOK_FOR_KEYS: 0
      DJANGO_SETTINGS_MODULE: webvirtcloud.settings.develop
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - mariadb
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    image: webvirtbackend:dev
    hostname: celery
    volumes:
      - .:/app
    command: celery -A webvirtcloud worker -l info
    environment:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: root
      PYTHONOPTIMIZE: 1
      ANSIBLE_HOST_KEY_CHECKING: 0
      ANSIBLE_PARAMIKO_LOOK_FOR_KEYS: 0
      DJANGO_SETTINGS_MODULE: webvirtcloud.settings.develop
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - rabbitmq
      - mariadb
  mariadb:
    image: mariadb:10.6.10
    hostname: mariadb
    volumes:
      - ./.mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: webvirtcloud
      MARIADB_USER: django
      MARIADB_PASSWORD: django
      MARIADB_ROOT_PASSWORD: root
  rabbitmq:
    image: rabbitmq:3.10.13
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest